packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

overrides:
  "@better-auth/core": "1.7.5"
  "@better-auth/utils": "0.5.0"
  "react": "19.2.8"
  "react-dom": "19.2.8"
  "esbuild": ">=0.25.0"
  "srvx": ">=0.11.13"

allowBuilds:
  "@sentry/cli": true
  "core-js": true
  "esbuild": true
  "msw": true
  "protobufjs": true
  "sharp": true

pmOnFail: ignore
