/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppRouteImport } from "./routes/_app";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as SignUpRouteImport } from "./routes/sign-up";
import { Route as TwoFactorRouteImport } from "./routes/two-factor";
import { Route as AppReaderRouteImport } from "./routes/_app/reader";
import { Route as AppSettingsRouteImport } from "./routes/_app/settings";
import { Route as ApiMcpRouteImport } from "./routes/api/mcp";
import { Route as ApiOpenapiDotjsonRouteImport } from "./routes/api/openapi[.]json";
import { Route as ApiOpmlRouteImport } from "./routes/api/opml";
import { Route as ApiReferenceRouteImport } from "./routes/api/reference";
import { Route as OauthConsentRouteImport } from "./routes/oauth/consent";
import { Route as DotwellKnownOauthAuthorizationServerSplatRouteImport } from "./routes/[.]well-known.oauth-authorization-server.$";
import { Route as DotwellKnownOauthProtectedResourceSplatRouteImport } from "./routes/[.]well-known.oauth-protected-resource.$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as ApiCronRefreshRouteImport } from "./routes/api/cron.refresh";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as ApiV1SplatRouteImport } from "./routes/api/v1.$";
import { Route as ApiWebhooksResendRouteImport } from "./routes/api/webhooks.resend";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const SignUpRoute = SignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any);
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: "/two-factor",
  path: "/two-factor",
  getParentRoute: () => rootRouteImport,
} as any);
const AppReaderRoute = AppReaderRouteImport.update({
  id: "/reader",
  path: "/reader",
  getParentRoute: () => AppRoute,
} as any);
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any);
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: "/api/mcp",
  path: "/api/mcp",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: "/api/openapi.json",
  path: "/api/openapi.json",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOpmlRoute = ApiOpmlRouteImport.update({
  id: "/api/opml",
  path: "/api/opml",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: "/api/reference",
  path: "/api/reference",
  getParentRoute: () => rootRouteImport,
} as any);
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: "/oauth/consent",
  path: "/oauth/consent",
  getParentRoute: () => rootRouteImport,
} as any);
const DotwellKnownOauthAuthorizationServerSplatRoute =
  DotwellKnownOauthAuthorizationServerSplatRouteImport.update({
    id: "/.well-known/oauth-authorization-server/$",
    path: "/.well-known/oauth-authorization-server/$",
    getParentRoute: () => rootRouteImport,
  } as any);
const DotwellKnownOauthProtectedResourceSplatRoute =
  DotwellKnownOauthProtectedResourceSplatRouteImport.update({
    id: "/.well-known/oauth-protected-resource/$",
    path: "/.well-known/oauth-protected-resource/$",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiCronRefreshRoute = ApiCronRefreshRouteImport.update({
  id: "/api/cron/refresh",
  path: "/api/cron/refresh",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: "/api/v1/$",
  path: "/api/v1/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: "/api/webhooks/resend",
  path: "/api/webhooks/resend",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/two-factor": typeof TwoFactorRoute;
  "/reader": typeof AppReaderRoute;
  "/settings": typeof AppSettingsRoute;
  "/api/mcp": typeof ApiMcpRoute;
  "/api/openapi.json": typeof ApiOpenapiDotjsonRoute;
  "/api/opml": typeof ApiOpmlRoute;
  "/api/reference": typeof ApiReferenceRoute;
  "/oauth/consent": typeof OauthConsentRoute;
  "/.well-known/oauth-authorization-server/$": typeof DotwellKnownOauthAuthorizationServerSplatRoute;
  "/.well-known/oauth-protected-resource/$": typeof DotwellKnownOauthProtectedResourceSplatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/cron/refresh": typeof ApiCronRefreshRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/api/v1/$": typeof ApiV1SplatRoute;
  "/api/webhooks/resend": typeof ApiWebhooksResendRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/two-factor": typeof TwoFactorRoute;
  "/reader": typeof AppReaderRoute;
  "/settings": typeof AppSettingsRoute;
  "/api/mcp": typeof ApiMcpRoute;
  "/api/openapi.json": typeof ApiOpenapiDotjsonRoute;
  "/api/opml": typeof ApiOpmlRoute;
  "/api/reference": typeof ApiReferenceRoute;
  "/oauth/consent": typeof OauthConsentRoute;
  "/.well-known/oauth-authorization-server/$": typeof DotwellKnownOauthAuthorizationServerSplatRoute;
  "/.well-known/oauth-protected-resource/$": typeof DotwellKnownOauthProtectedResourceSplatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/cron/refresh": typeof ApiCronRefreshRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/api/v1/$": typeof ApiV1SplatRoute;
  "/api/webhooks/resend": typeof ApiWebhooksResendRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_app": typeof AppRouteWithChildren;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/two-factor": typeof TwoFactorRoute;
  "/_app/reader": typeof AppReaderRoute;
  "/_app/settings": typeof AppSettingsRoute;
  "/api/mcp": typeof ApiMcpRoute;
  "/api/openapi.json": typeof ApiOpenapiDotjsonRoute;
  "/api/opml": typeof ApiOpmlRoute;
  "/api/reference": typeof ApiReferenceRoute;
  "/oauth/consent": typeof OauthConsentRoute;
  "/.well-known/oauth-authorization-server/$": typeof DotwellKnownOauthAuthorizationServerSplatRoute;
  "/.well-known/oauth-protected-resource/$": typeof DotwellKnownOauthProtectedResourceSplatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/cron/refresh": typeof ApiCronRefreshRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/api/v1/$": typeof ApiV1SplatRoute;
  "/api/webhooks/resend": typeof ApiWebhooksResendRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/forgot-password"
    | "/sign-in"
    | "/sign-up"
    | "/two-factor"
    | "/reader"
    | "/settings"
    | "/api/mcp"
    | "/api/openapi.json"
    | "/api/opml"
    | "/api/reference"
    | "/oauth/consent"
    | "/.well-known/oauth-authorization-server/$"
    | "/.well-known/oauth-protected-resource/$"
    | "/api/auth/$"
    | "/api/cron/refresh"
    | "/api/rpc/$"
    | "/api/v1/$"
    | "/api/webhooks/resend";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/forgot-password"
    | "/sign-in"
    | "/sign-up"
    | "/two-factor"
    | "/reader"
    | "/settings"
    | "/api/mcp"
    | "/api/openapi.json"
    | "/api/opml"
    | "/api/reference"
    | "/oauth/consent"
    | "/.well-known/oauth-authorization-server/$"
    | "/.well-known/oauth-protected-resource/$"
    | "/api/auth/$"
    | "/api/cron/refresh"
    | "/api/rpc/$"
    | "/api/v1/$"
    | "/api/webhooks/resend";
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/forgot-password"
    | "/sign-in"
    | "/sign-up"
    | "/two-factor"
    | "/_app/reader"
    | "/_app/settings"
    | "/api/mcp"
    | "/api/openapi.json"
    | "/api/opml"
    | "/api/reference"
    | "/oauth/consent"
    | "/.well-known/oauth-authorization-server/$"
    | "/.well-known/oauth-protected-resource/$"
    | "/api/auth/$"
    | "/api/cron/refresh"
    | "/api/rpc/$"
    | "/api/v1/$"
    | "/api/webhooks/resend";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  SignInRoute: typeof SignInRoute;
  SignUpRoute: typeof SignUpRoute;
  TwoFactorRoute: typeof TwoFactorRoute;
  ApiMcpRoute: typeof ApiMcpRoute;
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute;
  ApiOpmlRoute: typeof ApiOpmlRoute;
  ApiReferenceRoute: typeof ApiReferenceRoute;
  OauthConsentRoute: typeof OauthConsentRoute;
  DotwellKnownOauthAuthorizationServerSplatRoute: typeof DotwellKnownOauthAuthorizationServerSplatRoute;
  DotwellKnownOauthProtectedResourceSplatRoute: typeof DotwellKnownOauthProtectedResourceSplatRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiCronRefreshRoute: typeof ApiCronRefreshRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
  ApiV1SplatRoute: typeof ApiV1SplatRoute;
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forgot-password": {
      id: "/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-up": {
      id: "/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof SignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/two-factor": {
      id: "/two-factor";
      path: "/two-factor";
      fullPath: "/two-factor";
      preLoaderRoute: typeof TwoFactorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/reader": {
      id: "/_app/reader";
      path: "/reader";
      fullPath: "/reader";
      preLoaderRoute: typeof AppReaderRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/settings": {
      id: "/_app/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AppSettingsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/api/mcp": {
      id: "/api/mcp";
      path: "/api/mcp";
      fullPath: "/api/mcp";
      preLoaderRoute: typeof ApiMcpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/openapi.json": {
      id: "/api/openapi.json";
      path: "/api/openapi.json";
      fullPath: "/api/openapi.json";
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/opml": {
      id: "/api/opml";
      path: "/api/opml";
      fullPath: "/api/opml";
      preLoaderRoute: typeof ApiOpmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/reference": {
      id: "/api/reference";
      path: "/api/reference";
      fullPath: "/api/reference";
      preLoaderRoute: typeof ApiReferenceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/oauth/consent": {
      id: "/oauth/consent";
      path: "/oauth/consent";
      fullPath: "/oauth/consent";
      preLoaderRoute: typeof OauthConsentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/oauth-authorization-server/$": {
      id: "/.well-known/oauth-authorization-server/$";
      path: "/.well-known/oauth-authorization-server/$";
      fullPath: "/.well-known/oauth-authorization-server/$";
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/oauth-protected-resource/$": {
      id: "/.well-known/oauth-protected-resource/$";
      path: "/.well-known/oauth-protected-resource/$";
      fullPath: "/.well-known/oauth-protected-resource/$";
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/cron/refresh": {
      id: "/api/cron/refresh";
      path: "/api/cron/refresh";
      fullPath: "/api/cron/refresh";
      preLoaderRoute: typeof ApiCronRefreshRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/v1/$": {
      id: "/api/v1/$";
      path: "/api/v1/$";
      fullPath: "/api/v1/$";
      preLoaderRoute: typeof ApiV1SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/webhooks/resend": {
      id: "/api/webhooks/resend";
      path: "/api/webhooks/resend";
      fullPath: "/api/webhooks/resend";
      preLoaderRoute: typeof ApiWebhooksResendRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AppRouteChildren {
  AppReaderRoute: typeof AppReaderRoute;
  AppSettingsRoute: typeof AppSettingsRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppReaderRoute: AppReaderRoute,
  AppSettingsRoute: AppSettingsRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TwoFactorRoute: TwoFactorRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiOpmlRoute: ApiOpmlRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  OauthConsentRoute: OauthConsentRoute,
  DotwellKnownOauthAuthorizationServerSplatRoute:
    DotwellKnownOauthAuthorizationServerSplatRoute,
  DotwellKnownOauthProtectedResourceSplatRoute:
    DotwellKnownOauthProtectedResourceSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronRefreshRoute: ApiCronRefreshRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
