-- BetterAuth 1.7 schema: account identity scoped by issuer, OAuth protected
-- resources (RFC 8707) with grant-bound resource indicators, DPoP/back-channel
-- logout columns, refresh-token rotation replay window, two-factor lockout.
-- Generated by drizzle-kit; the issuer / application_type backfills are by hand
-- (see https://better-auth.com/docs/guides/1-7-upgrade-guide).
CREATE TABLE "oauth_client_assertions" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "oauth_client_resources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" text NOT NULL,
	"resource_id" text NOT NULL,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "oauth_resources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"identifier" text NOT NULL,
	"name" text NOT NULL,
	"access_token_ttl" integer,
	"refresh_token_ttl" integer,
	"signing_algorithm" text,
	"signing_key_id" text,
	"allowed_scopes" text[],
	"custom_claims" jsonb,
	"dpop_bound_access_tokens_required" boolean DEFAULT false,
	"disabled" boolean DEFAULT false,
	"policy_version" integer DEFAULT 1,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "oauth_resources_identifier_unique" UNIQUE("identifier")
);
--> statement-breakpoint
ALTER TABLE "oauth_clients" ALTER COLUMN "metadata" SET DATA TYPE jsonb USING nullif("metadata", '')::jsonb;--> statement-breakpoint
-- Account identity backfill: credential accounts already store the user id as
-- account_id; Google rows get the OIDC issuer; anything else the synthetic
-- local:oauth:<providerId> namespace.
ALTER TABLE "auth_accounts" ADD COLUMN "issuer" text;--> statement-breakpoint
UPDATE "auth_accounts" SET "issuer" = CASE "provider_id"
	WHEN 'credential' THEN 'local:credential'
	WHEN 'google' THEN 'https://accounts.google.com'
	ELSE 'local:oauth:' || "provider_id"
END;--> statement-breakpoint
ALTER TABLE "auth_accounts" ALTER COLUMN "issuer" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD COLUMN "resources" text[];--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD COLUMN "requested_user_info_claims" text[];--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD COLUMN "authorization_code_id" text;--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD COLUMN "confirmation" jsonb;--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD COLUMN "revoked" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "oauth_clients" ADD COLUMN "application_type" text;--> statement-breakpoint
ALTER TABLE "oauth_clients" ADD COLUMN "client_discovery_id" text;--> statement-breakpoint
ALTER TABLE "oauth_clients" ADD COLUMN "client_credentials_scopes" text[] DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "oauth_clients" ADD COLUMN "backchannel_logout_uri" text;--> statement-breakpoint
ALTER TABLE "oauth_clients" ADD COLUMN "backchannel_logout_session_required" boolean;--> statement-breakpoint
ALTER TABLE "oauth_clients" ADD COLUMN "jwks" text;--> statement-breakpoint
ALTER TABLE "oauth_clients" ADD COLUMN "jwks_uri" text;--> statement-breakpoint
ALTER TABLE "oauth_clients" ADD COLUMN "dpop_bound_access_tokens" boolean DEFAULT false;--> statement-breakpoint
-- `type` (web | native | user-agent-based) becomes RFC 7591 application_type;
-- public-ness is now derived from token_endpoint_auth_method = 'none'.
UPDATE "oauth_clients" SET "application_type" = CASE "type"
	WHEN 'web' THEN 'web'
	WHEN 'native' THEN 'native'
	ELSE NULL
END;--> statement-breakpoint
UPDATE "oauth_clients" SET "token_endpoint_auth_method" = 'none'
	WHERE "public" = true AND "token_endpoint_auth_method" IS NULL;--> statement-breakpoint
ALTER TABLE "oauth_consents" ADD COLUMN "resources" text[];--> statement-breakpoint
ALTER TABLE "oauth_consents" ADD COLUMN "requested_user_info_claims" text[];--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD COLUMN "resources" text[];--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD COLUMN "requested_user_info_claims" text[];--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD COLUMN "authorization_code_id" text;--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD COLUMN "confirmation" jsonb;--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD COLUMN "rotated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD COLUMN "rotation_replay_response" text;--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD COLUMN "rotation_replay_expires_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "auth_two_factor" ADD COLUMN "verified" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "auth_two_factor" ADD COLUMN "failed_verification_count" integer DEFAULT 0;--> statement-breakpoint
ALTER TABLE "auth_two_factor" ADD COLUMN "locked_until" timestamp;--> statement-breakpoint
ALTER TABLE "oauth_client_resources" ADD CONSTRAINT "oauth_client_resources_client_id_oauth_clients_client_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."oauth_clients"("client_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_client_resources" ADD CONSTRAINT "oauth_client_resources_resource_id_fk" FOREIGN KEY ("resource_id") REFERENCES "public"."oauth_resources"("identifier") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "oauth_client_resources_client_resource_uidx" ON "oauth_client_resources" USING btree ("client_id","resource_id");--> statement-breakpoint
CREATE UNIQUE INDEX "account_issuer_account_id_uidx" ON "auth_accounts" USING btree ("issuer","account_id");--> statement-breakpoint
ALTER TABLE "oauth_clients" DROP COLUMN "type";--> statement-breakpoint
ALTER TABLE "oauth_clients" DROP COLUMN "public";--> statement-breakpoint
ALTER TABLE "oauth_access_tokens" ADD CONSTRAINT "oauth_access_tokens_token_unique" UNIQUE("token");--> statement-breakpoint
ALTER TABLE "oauth_refresh_tokens" ADD CONSTRAINT "oauth_refresh_tokens_token_unique" UNIQUE("token");
