#!/usr/bin/env bash
# Discover Docker-assigned host ports for each service in docker-compose.yml
# and write them into .env.docker. The dev scripts load .env.docker in
# their dotenv chain so apps connect through the right port.
#
# Re-run after every `docker compose up -d`, recreate, or restart — the
# host port changes when Docker reassigns it. `pnpm deps:up` runs this
# automatically.

set -euo pipefail

cd "$(dirname "$0")/.."

# Resolve service:container-port → host port via `docker compose port`.
# Returns the host port number, or empty string if the service isn't up.
read_host_port() {
  local service=$1 internal=$2
  docker compose port "$service" "$internal" 2>/dev/null | awk -F: '{print $NF}' | head -1
}

PG_PORT=$(read_host_port postgres 5432)
PGWEB_PORT=$(read_host_port pgweb 8081)

if [[ -z "$PG_PORT" ]]; then
  echo "✗ postgres is not running. Run 'pnpm deps:up' first." >&2
  exit 1
fi

# Wait for postgres to accept connections (up to ~15s). Healthcheck takes a
# moment after the container starts; without this, db:migrate right after
# deps:up sometimes races the readiness probe.
for _ in {1..30}; do
  if docker compose exec -T postgres pg_isready -U dev -d app >/dev/null 2>&1; then
    break
  fi
  sleep 0.5
done

cat > .env.docker <<EOF
# ─── Auto-generated by scripts/sync-deps-env.sh ───────────────────────────
# Regenerated each time you run 'pnpm deps:up'. Host ports change every
# time the containers are recreated (after 'pnpm deps:down' or compose
# restart). Do not edit by hand — overrides belong in .env.local.

POSTGRES_URL=postgres://dev:dev@127.0.0.1:${PG_PORT}/app
TEST_DATABASE_URL=postgres://dev:dev@127.0.0.1:${PG_PORT}/app_test

# UI URLs (informational — for humans to copy into a browser)
PGWEB_URL=http://127.0.0.1:${PGWEB_PORT}
EOF

cat <<EOF
✓ wrote .env.docker
  postgres → 127.0.0.1:${PG_PORT}
  pgweb    → http://127.0.0.1:${PGWEB_PORT}
EOF
